var inventory = [
  // --- CAMERAS ---
  { type: "CAMERAS", category: "ARRI", desc: "ALEXA 35 extreme w/Case W/full Accessories", sn: "K1.0053455–70413", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "ARRI", desc: "ALEXA super 35 W/full accessories", sn: "K1.0039373–63715", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "SONY", desc: "BURANO CINE ALTA W/full accessories", sn: "6500005", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "SONY", desc: "Venice CINE ALTA W/full accessories", sn: "5–039–281–01", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "SONY", desc: "Venice CINE ALTA W/full accessories (2)", sn: "5–039–281–02", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "Black magic", desc: "ATEM SDI live Production switcher", sn: "10158840", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "ACTION", desc: "ACTION CAMERA", sn: "N/A", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "VR", desc: "360 CAMERA", sn: "N/A", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "VR", desc: "VR CAMERA", sn: "N/A", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "CODEX MEDIA", desc: "CODEX CARD READER (DC POWER)", sn: "1071254", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "CODEX MEDIA", desc: "CODEX CARD READER (USB-C)", sn: "1056305", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "CODEX MEDIA", desc: "CODEX CARD READER (USB-C) (2)", sn: "1076722", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "CODEX MEDIA", desc: "CODEX CARD READER (DC POWER) (2)", sn: "1075972", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "TERADEK", desc: "Transmitter/receiver", sn: "226400353", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "TERADEK", desc: "Transmitter/receiver (2)", sn: "226400546", qty: "1", status: "OK" },

  // --- MONITORS ---
  { type: "MONITORS", category: "ATOMOS", desc: "19 inch Directors monitor sumo 4K 60", sn: "K1 094SUM50D28", qty: "1", status: "OK" },
  { type: "MONITORS", category: "ATOMOS", desc: "19 inch Directors monitor sumo 4K 60 (2)", sn: "K2A94SUM50D89", qty: "1", status: "OK" },
  { type: "MONITORS", category: "SMALLHD", desc: "Monitor ultra 7 W/Teradeck bolt 6 RX 750", sn: "U7BS242290057", qty: "1", status: "OK" },
  { type: "MONITORS", category: "SMALLHD", desc: "Monitor ultra 7 W/Teradeck bolt 6 RX 750 (2)", sn: "U7BS241090377", qty: "1", status: "OK" },
  { type: "MONITORS", category: "SMALLHD", desc: "CINE 18 inch monitor", sn: "18AS241700002", qty: "1", status: "OK" },
  { type: "MONITORS", category: "SMALLHD", desc: "CINE 18 inch monitor (2)", sn: "18AS241700012", qty: "1", status: "OK" },
  { type: "MONITORS", category: "SMALLHD", desc: "CINE 13” monitor", sn: "13DS230800002", qty: "1", status: "OK" },
  { type: "MONITORS", category: "SMALLHD", desc: "CINE 5 ONBOARD MONITOR", sn: "C5AS24290016", qty: "1", status: "OK" },

  // --- BATTERIES ---
  { type: "BATTERIES", category: "SWIT", desc: "CHARGE STATION 4x4 B-MOUNT", sn: "1193980", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "SWIT", desc: "CHARGE STATION 4x4 B-MOUNT (2)", sn: "1022898", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "SWIT", desc: "B-MOUNT BATTERY BIVO 290", sn: "1085538", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "SWIT", desc: "B-MOUNT BATTERY BIVO 290 (2)", sn: "119638", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "SWIT", desc: "B-MOUNT BATTERY BIVO 290 (3)", sn: "1173952", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "SWIT", desc: "B-MOUNT BATTERY BIVO 290 (4)", sn: "1085696", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "BLUESHAPE", desc: "B-MOUNT BATTERY 290 GRANITE", sn: "0074251–51", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "BLUESHAPE", desc: "B-MOUNT BATTERY 290 GRANITE (2)", sn: "0031251–28", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "BLUESHAPE", desc: "B-MOUNT BATTERY 290 GRANITE (3)", sn: "0076151–56", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "BLUESHAPE", desc: "B-MOUNT BATTERY 290 GRANITE (4)", sn: "0076251–5F", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "DJI", desc: "BATTERY STATION - TB50", sn: "IN2BS", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "SMALLHD", desc: "24” DC/ V-MOUNT BATTERY RACK", sn: "24DS240850007", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "SMALLHD", desc: "24” DC/ V-MOUNT BATTERY RACK (2)", sn: "24DS251180009", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "GENERIC", desc: "BATTERY", sn: "N/A", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "GENERIC", desc: "CHARGER", sn: "N/A", qty: "1", status: "OK" },
  { type: "BATTERIES", category: "GENERIC", desc: "POWER SUPPLY", sn: "N/A", qty: "1", status: "OK" },

  // --- LENSES ---
  { type: "LENSES", category: "DZOFILM", desc: "PAVO 28mm T2.9", sn: "70510146", qty: "1", status: "OK" },
  { type: "LENSES", category: "DZOFILM", desc: "PAVO 40mm T2.9", sn: "72510332", qty: "1", status: "OK" },
  { type: "LENSES", category: "DZOFILM", desc: "PAVO 75mm T2.9", sn: "75410269", qty: "1", status: "OK" },
  { type: "LENSES", category: "COOKE", desc: "85 mm anamorphic 1.8 macro lens", sn: "7085–5283", qty: "1", status: "OK" },
  { type: "LENSES", category: "COOKE", desc: "32mm 2x ANAMORPHIC", sn: "9032-0147", qty: "1", status: "OK" },
  { type: "LENSES", category: "COOKE", desc: "50mm 2x ANAMORPHIC", sn: "9050-0147", qty: "1", status: "OK" },
  { type: "LENSES", category: "THYPOCH", desc: "21mm T1.5 SIMERA-C", sn: "W14J7100533", qty: "1", status: "OK" },
  { type: "LENSES", category: "THYPOCH", desc: "28mm T1.5 SIMERA-C", sn: "W13G7100387", qty: "1", status: "OK" },
  { type: "LENSES", category: "FF RANGER", desc: "28/75mm T2.9 ZOOM", sn: "PL900032", qty: "1", status: "OK" },
  { type: "LENSES", category: "FF RANGER", desc: "75/180mm T2.9 ZOOM", sn: "PL900126", qty: "1", status: "OK" },
  { type: "LENSES", category: "GENERIC", desc: "LENS ADAPTER", sn: "N/A", qty: "1", status: "OK" },

  // --- FILTERS ---
  { type: "FILTERS", category: "TIFFEN", desc: "WTR/WHT ND 1.2", sn: "303448", qty: "1", status: "OK" },
  { type: "FILTERS", category: "TIFFEN", desc: "WTR/WHT ND .6", sn: "302563", qty: "1", status: "OK" },
  { type: "FILTERS", category: "TIFFEN", desc: "BLACK PRO-MIST 1/2", sn: "70921", qty: "1", status: "OK" },
  { type: "FILTERS", category: "TIFFEN", desc: "CLEAR/ND.9 SOFT HOR", sn: "88674", qty: "1", status: "OK" },
  { type: "FILTERS", category: "SCHNEIDER", desc: "TRUE-STREAK / YELLOW 3mm", sn: "68-507356", qty: "1", "status": "OK" },
  { type: "FILTERS", category: "NiSi", desc: "ALLURE STREAK BLUE 2mm", sn: "NIC-4565-ASTB2", qty: "1", "status": "OK" },
  { type: "FILTERS", category: "ARRI", desc: "ROTA POLA", sn: "K2.0017086", qty: "2", "status": "OK" },
  { type: "FILTERS", category: "LINDSEY", desc: "CLOSE-UP DIOPTER +1/2", sn: "A10240", qty: "1", "status": "OK" },
  { type: "FILTERS", category: "TILTA", desc: "Matt Box 6x6 W/accessories", sn: "N/A", qty: "2", "status": "OK" },
  { type: "FILTERS", category: "BRIGHT Tangerine", desc: "Matt Box 4,5,6 W/accessories", sn: "NA", qty: "1", "status": "OK" },

  // --- TRIPODS ---
  { type: "TRIPODS", category: "Cartoni", desc: "Tripod legs 10mm bowl W/ Focus 18", sn: "FG1108", qty: "1", "status": "OK" },
  { type: "TRIPODS", category: "O’Connor", desc: "Tripod legs TALL", sn: "N/A", qty: "2", "status": "OK" },
  { type: "TRIPODS", category: "Pro aim", desc: "High hat with wooden base", sn: "N/A", qty: "1", "status": "OK" },
  { type: "TRIPODS", category: "A-R CINE", desc: "Tripod medium", sn: "NA", qty: "2", "status": "OK" },
  { type: "TRIPODS", category: "A-R CINE", desc: "Tripod carbon fiber tall", sn: "NA", qty: "1", "status": "OK" },
  { type: "TRIPODS", category: "CARTONI", desc: "MAXIMA 5.0 fluid head 150mm", sn: "MX0743", qty: "1", "status": "OK" },
  { type: "TRIPODS", category: "OCONNOR", desc: "Ultimate 2575D fluid head 150mm", sn: "NA", qty: "2", "status": "OK" },
  { type: "TRIPODS", category: "SACHTLER", desc: "Baby legs W/ ground spreader", sn: "NA", qty: "1", "status": "OK" },
  
  // --- LIGHTING ---
  { type: "LIGHTING", category: "Apurture", desc: "INFINIBAR 8 pieces", sn: "4000–999–028", qty: "8", "status": "OK" },
  { type: "LIGHTING", category: "Apurture", desc: "Light storm 60 X", sn: "TBD", qty: "1", "status": "OK" },
  { type: "LIGHTING", category: "Apurture", desc: "INFINIMAT inflatable soft box 1X2", sn: "7DRDBH10205B", qty: "1", "status": "OK" },
  { type: "LIGHTING", category: "ZHIYUN", desc: "MOLUS light kit", sn: "9060890C3010071", qty: "3", "status": "OK" },
  { type: "LIGHTING", category: "TILTA", desc: "TA-LSR-B SHOULDER RIG KIT", sn: "SKU:6937134600285", qty: "1", "status": "OK" },
  { type: "LIGHTING", category: "GENERIC", desc: "LIGHT STAND WITH BOOM ARM", sn: "N/A", qty: "1", "status": "OK" },

  // --- GRIP ---
  { type: "GRIP", category: "MOV MAX", desc: "Grip Dolly pro kit", sn: "DL – 20341005006", qty: "1", "status": "OK" },
  { type: "GRIP", category: "Pro aim", desc: "Action–King 8” Car mount", sn: "CM – ACKG – 02", qty: "1", "status": "OK" },
  { type: "GRIP", category: "Pro aim", desc: "CINEBIRD RICKSHAW SUPPORT", sn: "RCSW-CNBD-01", qty: "1", "status": "OK" },
  { type: "GRIP", category: "Pro aim", desc: "AIRWAVE V-15 VIBRATION ISOLATOR", sn: "VI-ARWV-15", qty: "1", "status": "OK" },
  { type: "GRIP", category: "Pro aim", desc: "MITCHELL MOUNT", sn: "P-MTCL-RGCL", qty: "1", "status": "OK" },
  { type: "GRIP", category: "Pro aim", desc: "Ridgeline CINE sled", sn: "NA", qty: "1", "status": "OK" },
  { type: "GRIP", category: "Mag liner", desc: "Two tier cart", sn: "N/A", qty: "1", "status": "OK" },
  { type: "GRIP", category: "CINETICA", desc: "RISER 700", sn: "N/A", qty: "1", "status": "Unknown" },
  { type: "GRIP", category: "Custom easy", desc: "Raptor magnet with case", sn: "TBD", qty: "1", "status": "OK" },
  { type: "GRIP", category: "ROBOJIB", desc: "P720 PRO full kit", sn: "No", qty: "1", "status": "Unknown" },
  { type: "GRIP", category: "HYDRA ARM", desc: "Remote control system", sn: "TBD", qty: "1", "status": "OK" },
  { type: "GRIP", category: "CINEGEAR", desc: "Electronic/Car mount suction", sn: "ESC6", qty: "10", "status": "OK" },
  { type: "GRIP", category: "G – KA LUNA", desc: "Motion control, robotic arm", sn: "6528", qty: "1", "status": "OK" },
  { type: "GRIP", category: "FLYCAM", desc: "Wake-up Cam vest", sn: "N/A", qty: "1", "status": "OK" },
  { type: "GRIP", category: "HERMIT", desc: "HERMIT HELMET POV MOUNT", sn: "N/A", qty: "1", "status": "OK" },
  { type: "GRIP", category: "EASY-RIG", desc: "EASY-RIG five gimbal rig", sn: "VG5S2STQ", qty: "1", "status": "OK" },
  { type: "GRIP", category: "C-STAND", desc: "C-STAND WITH BOOM ARM", sn: "N/A", qty: "1", "status": "OK" },
  { type: "GRIP", category: "O’Connor", desc: "Euro plate adapter", sn: "2575–120", qty: "2", "status": "OK" },
  { type: "GRIP", category: "Clamp", desc: "Friction arm clamp", sn: "NA", qty: "2", "status": "OK" },
  { type: "GRIP", category: "Blower", desc: "Handheld blower for cleaning", sn: "N/A", qty: "1", "status": "OK" },
  { type: "GRIP", category: "NOGA CINE", desc: "NOGA CINE ARMS", sn: "NA", qty: "1", "status": "OK" },
  { type: "GRIP", category: "SMALL RIG", desc: "Small rig friction arm", sn: "NA", qty: "1", "status": "OK" },
  { type: "GRIP", category: "City Gear", desc: "C360HD-20 HEAVY-DUTY ROTATING RIG", sn: "CGF–SG–C360HD–20", qty: "1", "status": "OK" },
  { type: "GRIP", category: "PANTHER", desc: "CLASSIC PLUS WHEEL & TRACK SYSTEM", sn: "02-293-23", qty: "1", "status": "OK" },
  { type: "GRIP", category: "FREEFLY", desc: "MoVI PRO GIMBAL STABILIZER SYSTEM", sn: "950–0019", qty: "1", "status": "OK" },
  { type: "GRIP", category: "FLOWCINE", desc: "DOUBLE-SECTION ARTICULATED STABILIZATION ARM", sn: "FC-X-XARM", qty: "1", "status": "OK" },
  { type: "GRIP", category: "GENERIC", desc: "SANDBAG", sn: "N/A", qty: "1", "status": "OK" },
  { type: "GRIP", category: "GENERIC", desc: "CLAMPS", sn: "N/A", qty: "1", "status": "OK" },
  { type: "GRIP", category: "ROBO CUP", desc: "CLAMP CUP HOLDER", sn: "N/A", qty: "2", "status": "OK" },
  { type: "GRIP", category: "LOUD SPEAKER", desc: "12” PROFESSIONAL SPEAKER", sn: "LSA – 12DSP", qty: "1", "status": "OK" },

  // --- AUDIO ---
  { type: "AUDIO", category: "BOYA", desc: "Directors mic w/ transmitter", sn: "4287", qty: "1", "status": "OK" },
  { type: "AUDIO", category: "DEITY", desc: "THEOS DIGITAL UHF WIRELESS", sn: "7DDDBL1020B9", qty: "1", "status": "OK" },
  { type: "AUDIO", category: "DEITY", desc: "TC-1 WIRELESS MICROPHONES", sn: "6NR00088927", qty: "1", "status": "OK" },
  { type: "AUDIO", category: "DEITY", desc: "PR-2 STEREO RECORDER", sn: "7CJ00077881", qty: "1", "status": "OK" },
  { type: "AUDIO", category: "ZOOM", desc: "H6 AUDIO RECORDER", sn: "91523425", qty: "1", "status": "OK" },
  { type: "AUDIO", category: "ZOOM", desc: "F6 MULTI-TRACK FIELD RECORDER", sn: "007077", qty: "1", "status": "OK" },
  { type: "AUDIO", category: "SENNHEISER", desc: "MKH 416 P48", sn: "230382", qty: "1", "status": "OK" },
  
  // SUPPORT ITEMS (Put in Cameras or Grip)
  { type: "CAMERAS", category: "ARRI", desc: "Handset for handheld", sn: "NA", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "BRIGHT Tangerine", desc: "Handset for handheld", sn: "NA", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "BRIGHT Tangerine", desc: "9 inch cine rods", sn: "NA", qty: "2", status: "OK" },
  { type: "CAMERAS", category: "SMALLHD", desc: "Ultra 7 sunshade W/rods", sn: "NA", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "TILTA", desc: "Utility Allen key set", sn: "N/A", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "ARRI", desc: "Proprietary Alan key red handle", sn: "SW3X75", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "HI-5", desc: "SX Hi-5 hand unit, 2 batt, charger", sn: "k2.0073280–63084", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "HI-5", desc: "Hi-5 hand unit, 2 batt, charger", sn: "k2.0037280–61715", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "C-MOTION", desc: "CINIEFADE VARI360 kit w/ limo control", sn: "K2.0019848–8023", qty: "1", status: "OK" },
  { type: "CAMERAS", category: "HOLLYLAND", desc: "SOLIDCOM C1 Pro W/case", sn: "45HX4423KUT", qty: "11", status: "OK" },
  { type: "CAMERAS", category: "TILTA", desc: "Manual focus W/bridge brace", sn: "NA", qty: "2", status: "OK" }
];
