const inventory = [
  { "type": "Grip", "category": "MOV MAX", "desc": "Grip Dolly pro kit, with flight case", "sn": "DL – 20341005006", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Pro aim", "desc": "High hat with wooden base", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Cartoni", "desc": "Tripod legs 10 mm bowl W/ Focus 18 head", "sn": "Legs:T628/2   Head: FG1108", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Apurture", "desc": "INFINIBAR 8 pieces 1 missing", "sn": "4000–999–028", "qty": "8", "status": "OK" },
  { "type": "Camera", "category": "O’Connor", "desc": "Camera support system/tripod legs TALL", "sn": "N/A", "qty": "2", "status": "OK" },
  { "type": "Grip", "category": "Pro aim", "desc": "Action–King 8” Car mount camera 48 mm suction kit", "sn": "CM – ACKG – 02", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Apurture", "desc": "Light storm 60 X", "sn": "TBD", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Apurture", "desc": "INFINIMAT inflatable soft box 1X2", "sn": "7DRDBH10205B", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Mag liner #1", "desc": "Two tier", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CINETICA", "desc": "RISER 700", "sn": "N/A", "qty": "1", "status": "Unknown" },
  { "type": "Grip", "category": "CINETICA", "desc": "AU.TRON 4.0", "sn": "N/A", "qty": "1", "status": "Unknown" },
  { "type": "Grip", "category": "Custom easy", "desc": "Raptor magnet with case", "sn": "TBD", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "FALCAM", "desc": "Move lightGO/BOWENS Mount", "sn": "907001100501299", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "ROBOJIB", "desc": "P720 PRO full kit with wheels and counterweights", "sn": "No", "qty": "1", "status": "Unknown" },
  { "type": "Grip", "category": "HYDRA ARM", "desc": "Remote control system handheld", "sn": "TBD", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "HYDRA ARM", "desc": "3 tier pole system for Chase car", "sn": "TBD", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "HYDRA ARM", "desc": "TILTA mini Hydra Arm W/shock absorber", "sn": "TBD", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "ZHIYUN", "desc": "MOLUS light kit w/ batteries, soft box, case", "sn": "9060890C3010071", "qty": "3", "status": "OK" },
  { "type": "Grip", "category": "Apurture", "desc": "INFINIBAR PB6 W/hard case, spigot, mounting plate", "sn": "7AEDAC102571", "qty": "2", "status": "OK" },
  { "type": "Grip", "category": "HOLLYLAND", "desc": "SOLIDCOM C1 Pro W/case, batteries, charge system", "sn": "45HX4423KUT/2223220TXC008774", "qty": "11", "status": "OK" },
  { "type": "Grip", "category": "CINEGEAR factory", "desc": "Electronic/ Car mount suction cups", "sn": "ESC6", "qty": "10", "status": "OK" },
  { "type": "Grip", "category": "G – KA LUNA", "desc": "Motion control, robotic arm/slide deck/remote", "sn": "GKALUNA – 6528/T32500764BL", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "PDMOVIE", "desc": "LIVE AIR 3 SMART flash mini", "sn": "PD – BTMP – S 004847", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "K&F", "desc": "Step up and step down rings", "sn": "N/A", "qty": "11", "status": "OK" },
  { "type": "Grip", "category": "Black magic design", "desc": "ATEM SDI live Production switcher with broadcast", "sn": "10158840", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BOYA", "desc": "Directors mic w/ transmitter / BY – WM8 Pro receiver", "sn": "4287", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "FLYCAM VEST", "desc": "Wake-up Cam vest/ run POV vest", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "HERMIT HELMET", "desc": "HERMIT HELMET, POV CAM MOUNT W/CASE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "6 point lock", "desc": "Gnarled spigot W/6 point lockdown", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Mag liner #2", "desc": "3 tier mag liner W/trays X 2", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Grip stands", "desc": "Grip stands Dolly", "sn": "N/A", "qty": "1", "status": "Unknown" },
  { "type": "Grip", "category": "Hudson spider SLDR", "desc": "Slider W/case, W/150 mm bowl attachment", "sn": "N/A", "qty": "1", "status": "Unknown" },
  { "type": "Camera", "category": "ARRI Camera", "desc": "ARRI ALEXA 35 extreme w/Case W/full Accessories", "sn": "K1.0053455–70413", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "AARI Camera", "desc": "AARI ALEXA super 35 W/full accessories", "sn": "K1.0039373–63715", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ARRI Camera", "desc": "ARRI ALEXA super 35 W/full accessories", "sn": "K1.0047337–50302", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SONY Camera", "desc": "Sony BURANO CINE ALTA W/full accessories", "sn": "6500005", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SONY Camera", "desc": "Sony Venice CINE ALTA W/full accessories", "sn": "5–039–281–01", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SONY Camera", "desc": "Sony Venice CINE ALTA W/full accessories", "sn": "5–039–281–02", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TILTA", "desc": "Matt Box 6 x 6 W/full accessories", "sn": "N/A", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "TILTA", "desc": "Matt Box 4,5,6 W/full accessories", "sn": "N/A", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "BRIGHT Tangerine", "desc": "Matt Box 4,5,6 W/full accessories", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BRIGHT Tangerine", "desc": "Matt box 6 x 6 W/full access accessories", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "A-R CINE tripod", "desc": "A-R CINE tripod medium", "sn": "NA", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "A-R CINE tripod", "desc": "A-R CINE tripod carbon fiber tall", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CARTONI", "desc": "CARTONI MAXIMA 5.0 fluid head 150 mm bowl", "sn": "MX0743", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "OCONNOR", "desc": "Ultimate 2575D fluid head 150 mm bowl", "sn": "NA", "qty": "2", "status": "OK" },
  { "type": "Grip", "category": "A-R CINE", "desc": "A-R CINE 150 mm bowl high hat, black", "sn": "NA", "qty": "2", "status": "OK" },
  { "type": "Grip", "category": "EASY-RIG ACE", "desc": "EASY-RIG five gimbal rig stabilizer vest overhead", "sn": "VG5S2STQ", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SACHTLER", "desc": "Baby legs W/ ground spreader", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TILTA", "desc": "Manual focus W/bridge brace 15 mm/19 mm", "sn": "NA", "qty": "2", "status": "OK" },
  { "type": "Grip", "category": "City Gear Factory", "desc": "C360HD-20 HEAVY-DUTY ROTATING RIG W/CASE 6.6", "sn": "CGF – SG – C360HD – 20", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "PROAIM", "desc": "Ridgeline CINE sled W/multi point attachment", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Mag liner #3", "desc": "2 tier wide wheel camera cart, W/accessories", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ATOMOS", "desc": "19 inch Directors monitor sumo 4K 60", "sn": "K1 094SUM50D28", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ATOMOS", "desc": "19 inch Directors monitor sumo 4K 60", "sn": "K2A94SUM50D89", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD monitor ultra 7 W/Teradeck bolt 6 RX 750", "sn": "U7BS242290057", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD monitor ultra 7 W/Teradeck bolt 6 RX 750", "sn": "U7BS241090377", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD CINE 18 inch monitor", "sn": "18AS241700002", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD CINE 18 inch monitor", "sn": "18AS241700012", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TERADEK", "desc": "Transmitter/receiver", "sn": "226400353", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TERADEK", "desc": "Transmitter/receiver", "sn": "226400546", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "O’Connor", "desc": "Euro plate adapter", "sn": "2575–120", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "DZOFILM PAVO", "desc": "28mm W/shims, rods, bayonet, screwdriver set, case", "sn": "70510146", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DZOFILM PAVO", "desc": "40 mm W/shims, rods, bayonet, screwdriver set,case", "sn": "72510332", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DZOFILM PAVO", "desc": "65 mm W/shims, rods, bayonet, screwdriver set, case", "sn": "1J10100", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DZOFILM PAVO", "desc": "75 mm W/shims, rods, bayonet, screwdriver set, case", "sn": "75410269", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DZOFILM PAVO", "desc": "135 mm W/shims, rods, bayonet, screwdriver set, case", "sn": "76610185", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DZOFILM PAVO", "desc": "180 mm W/shims, rods, bayonet, screwdriver set, case", "sn": "1K610134", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "COOKE LENS", "desc": "85 mm anamorphic 1.8 macro lens", "sn": "7085–5283", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "Clamp", "desc": "Friction arm clamp", "sn": "NA", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "ARRI", "desc": "Handset for handheld", "sn": "NA", "qty": "One set", "status": "OK" },
  { "type": "Camera", "category": "BRIGHT Tangerine", "desc": "Handset for handheld", "sn": "NA", "qty": "One set", "status": "OK" },
  { "type": "Grip", "category": "Blower", "desc": "Handheld blower for cleaning", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "NOGA CINE", "desc": "NOGA CINE ARMS", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BRIGHT Tangerine", "desc": "9 inch cine rods", "sn": "NA", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Ultra 7 sunshade W/rods", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SDI cable", "desc": "SDI cable", "sn": "NA", "qty": "3", "status": "OK" },
  { "type": "Grip", "category": "LIMO cable", "desc": "LIMO cable", "sn": "NA", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "TILTA", "desc": "Utility Allen key set", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ARRI", "desc": "Proprietary Alan key red handle", "sn": "SW3X75", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SMALL RIG", "desc": "Small rig friction arm", "sn": "NA", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "HI-5 (BLUE)", "desc": "SX Hi-5 hand unit, 2 batt, charger, Antenna Unit, case", "sn": "k2.0073280–63084", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "HI-5 (BLACK)", "desc": "Hi-5 hand unit, 2 batt, charger, Antenna Unit, case", "sn": "k2.0037280–61715", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "C-MOTION", "desc": "CINIEFADE VARI360 kit w/ limo control 4 pin, w/case", "sn": "K2.0019848–8023", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "WTR/WHT ND 1.2", "sn": "303448", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "WTR/WHT ND .3", "sn": "303439", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "WTR/WHT ND .6", "sn": "302563", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "WTR/WHT ND .9", "sn": "303436", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "GLIMMER GLASS TM 1", "sn": "53329", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "BLACK PRO-MIST 1/2", "sn": "70921", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "BLACK PRO-MIST 1/4", "sn": "52949", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "CLEAR/ND.9 SOFT HOR", "sn": "88674", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "WTR/WHT CLEAR/N.9 SOFT HOR", "sn": "82558", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SCHNEIDER KREUZNACH", "desc": "TRUE-STREAK / YELLOW 3mm", "sn": "68-507356", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "NiSi", "desc": "ALLURE STREAK BLUE 2mm", "sn": "NIC-4565-ASTB2", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "CLEAR", "sn": "82790", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "NiSi", "desc": "PURE CLEAR", "sn": "ASIN: B08ZX7PFBS", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "NiSi", "desc": "IR ND 0.6 / 2 STOP", "sn": "ASIN: B017ILUK5S", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "NiSi", "desc": "IR ND 0.3 / 1 STOP", "sn": "6971634248059", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "TIFFEN", "desc": "BLACK PRO-MIST 1", "sn": "201705", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ARRI", "desc": "ROTA POLA", "sn": "K2.0017086", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "LINDSEY OPTICS", "desc": "CLOSE-UP DIOPTER +1/2", "sn": "A10240", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "LINDSEY OPTICS", "desc": "CLOSE-UP DIOPTER +1", "sn": "Z1945", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "LINDSEY OPTICS", "desc": "CLOSE-UP DIOPTER +2", "sn": "A11936-D", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "LINDSEY OPTICS", "desc": "CLOSE-UP DIOPTER +3", "sn": "A9722", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BRIGHT TANGERINE", "desc": "MATT BOX CARBON FIBER 6 x 6", "sn": "B1245.0103", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SUPPORT RODS", "desc": "4” BLACK SUPPORT RODS 15mm", "sn": "N/A", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "COOKE LENSES", "desc": "32mm 2x’s ANAMORPHIC LENS, W/CASE", "sn": "9032-0147", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "COOKE LENSES", "desc": "40mm 2x’s ANAMORPHIC LENS, W/CASE", "sn": "9040-0147", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "COOKE LENSES", "desc": "50mm 2x’s ANAMORPHIC LENS, W/CASE", "sn": "9050-0147", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "COOKE LENSES", "desc": "75mm 2x’s ANAMORPHIC LENS, W/CASE", "sn": "9075-0147", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "COOKE LENSES", "desc": "100mm 2x’s ANAMORPHIC LENS, W/CASE", "sn": "9100-0147", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "COOKE LENSES", "desc": "135mm 2x’s ANAMORPHIC LENS, W/CASE", "sn": "9135-0147", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "AC STAND", "desc": "1st AC STAND", "sn": "719821302957", "qty": "4", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "24” DC/ V-MOUNT BATTERY RACK", "sn": "24DS240850007", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD monitor CINE 24” DC/ V-MOUNT BATTERY RACK", "sn": "24DS251180009", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "FLOWCINE X-ARM", "desc": "DOUBLE-SECTION ARTICULATED STABILIZATION ARM", "sn": "FC-X-XARM", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "FF RANGER PRIME LENS", "desc": "28/75mm T2.9", "sn": "PL900032", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "FF RANGER PRIME LENS", "desc": "75/180mm T2.9", "sn": "PL900126", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "THEOS DIGITAL UHF WIRELESS SYSTEM KIT", "sn": "7DDDBL1020B9", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "THEOS DIGITAL UHF WIRELESS SYSTEM KIT", "sn": "7DCDBL20205D", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "TC-1 WIRELESS MICROPHONES KIT TRANSMITTER/RECEIVER", "sn": "6NR00088927", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "TC-1 WIRELESS MICROPHONES KIT TRANSMITTER/RECEIVER", "sn": "6NR00062322", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "BP – TRX", "sn": "3Z00138965", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "BP – TRX", "sn": "3Z00138962", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "BP – TRX", "sn": "3Z00138950", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "D4 DUO V-MICROPHONES", "sn": "43900018318", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "D4 DUO V-MICROPHONES", "sn": "43900018338", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "SLATE TC-1", "sn": "6PQ00061806", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "PR-2 STEREO RECORDER", "sn": "7CJ00077881", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "PR-2 STEREO RECORDER", "sn": "7CJ00077890", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "PR-2 STEREO RECORDER", "sn": "7CJ00077895", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "PR-2 STEREO RECORDER", "sn": "7CJ00077884", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "PR-2 STEREO RECORDER", "sn": "7CJ00077892", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "W.LAV PRO/DA35", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "VO-7U", "sn": "52500021669", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "ASM1", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "SPD-1", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "C15/ LOCKING 3.5mm CLAMP", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "DA35S MICRO DOT ADAPTER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DEITY MICROPHONES", "desc": "W.LAV PRO 3.5mm", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ZOOM", "desc": "H6 AUDIO RECORDER HANDY RECORDER", "sn": "91523425", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ZOOM", "desc": "ZOOM F6 MULTI-TRACK FIELD RECORDER", "sn": "007077", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "LIGHT STAND", "desc": "LIGHT STAND WITH BOOM ARM", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "C-STAND", "desc": "C-STAND WITH BOOM ARM", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SUPPORT", "desc": "ADJUSTABLE BACKGROUND SUPPORT SYSTEM", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SOFT BOX", "desc": "SOFT BOX 60 X 90cm", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "REFLECTOR", "desc": "REFLECTOR 5 IN 1 110cm", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CLAMPS", "desc": "CLAMPS", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SANDBAG", "desc": "SANDBAG", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CARRYING BAG", "desc": "CARRYING BAG", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "FOG MACHINE", "desc": "FOG MACHINE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "HAZE MACHINE", "desc": "HAZE MACHINE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SNOW MACHINE", "desc": "SNOW MACHINE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "BUBBLE MACHINE", "desc": "BUBBLE MACHINE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "WIND MACHINE", "desc": "WIND MACHINE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "TURNTABLE", "desc": "TURNTABLE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "GIMBAL", "desc": "GIMBAL", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SLIDER", "desc": "SLIDER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "JIB", "desc": "JIB", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "DOLLY", "desc": "DOLLY", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "TRACK", "desc": "TRACK", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CRANE", "desc": "CRANE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DRONE", "desc": "DRONE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "ACTION CAMERA", "desc": "ACTION CAMERA", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "360 CAMERA", "desc": "360 CAMERA", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "VR CAMERA", "desc": "VR CAMERA", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "UNDERWATER CAMERA", "desc": "UNDERWATER CAMERA", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "HIGH SPEED CAMERA", "desc": "HIGH SPEED CAMERA", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "THERMAL CAMERA", "desc": "THERMAL CAMERA", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "NIGHT VISION CAMERA", "desc": "NIGHT VISION CAMERA", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "LENS ADAPTER", "desc": "LENS ADAPTER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "FILTER", "desc": "FILTER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "MEMORY CARD", "desc": "MEMORY CARD", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "HARD DRIVE", "desc": "HARD DRIVE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "CARD READER", "desc": "CARD READER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BATTERY", "desc": "BATTERY", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "CHARGER", "desc": "CHARGER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "POWER SUPPLY", "desc": "POWER SUPPLY", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CABLE", "desc": "CABLE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "ADAPTER", "desc": "ADAPTER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CONVERTER", "desc": "CONVERTER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SPLITTER", "desc": "SPLITTER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SWITCHER", "desc": "SWITCHER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "DISTRIBUTION AMPLIFIER", "desc": "DISTRIBUTION AMPLIFIER", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "SIGNAL PROCESSOR", "desc": "SIGNAL PROCESSOR", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "TEST EQUIPMENT", "desc": "TEST EQUIPMENT", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "TOOL", "desc": "TOOL", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "CONSUMABLE", "desc": "CONSUMABLE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "FURNITURE", "desc": "FURNITURE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "VEHICLE", "desc": "VEHICLE", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "GENERATOR", "desc": "GENERATOR", "sn": "N/A", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "ROBO CUP HOLDER", "desc": "CLAMP CUP HOLDER", "sn": "N/A", "qty": "2", "status": "OK" },
  { "type": "Camera", "category": "SWIT CHARGER STN", "desc": "SWIT CHARGE STATION 4x4 B-MOUNT BATTERIES", "sn": "1193980", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SWIT CHARGER STN", "desc": "SWIT CHARGE STATION 4x4 B-MOUNT BATTERIES", "sn": "1022898", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SWIT BATTERY", "desc": "SWIT B-MOUNT BATTERY BIVO 290", "sn": "1085538", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SWIT BATTERY", "desc": "SWIT B-MOUNT BATTERY BIVO 290", "sn": "119638", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SWIT BATTERY", "desc": "SWIT B-MOUNT BATTERY BIVO 290", "sn": "1173952", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SWIT BATTERY", "desc": "SWIT B-MOUNT BATTERY BIVO 290", "sn": "1085696", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BLUESHAPE BATTERY", "desc": "BLUESHAPE B-MOUNT BATTERY 290 GRANITE SMT", "sn": "0074251\u201351", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BLUESHAPE BATTERY", "desc": "BLUESHAPE B-MOUNT BATTERY 290 GRANITE SMT", "sn": "0031251\u201328", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BLUESHAPE BATTERY", "desc": "BLUESHAPE B-MOUNT BATTERY 290 GRANITE SMT", "sn": "0076151\u201356", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "BLUESHAPE BATTERY", "desc": "BLUESHAPE B-MOUNT BATTERY 290 GRANITE SMT", "sn": "0076251 \u20135F", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "PROAIM", "desc": "CINEBIRD RICKSHAW SUPPORT", "sn": "RCSW-CNBD-01", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "PROAIM", "desc": "AIRWAVE V-15 CAMERA VIBRATION ISOLATOR ARM", "sn": "VI-ARWV-15", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "PROAIM", "desc": "MITCHELL MOUNT", "sn": "P-MTCL-RGCL", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "FREEFLY", "desc": "FREEFLY MoVI PRO GIMBAL STABILIZER SYSTEM", "sn": "950\u20130019", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "PANTHER", "desc": "PANTHER CLASSIC PLUS WHEEL & TRACK SYSTEM", "sn": "02-293-23", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD monitor ultra 7 W/Teradeck bolt 6 RX 750", "sn": "U7BS242290052", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD monitor ultra 7 W/Teradeck bolt 6 RX 750", "sn": "C7AS250130293", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "CODEX MEDIA", "desc": "CODEX CARD READER (DC POWER)", "sn": "1075972", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "SMALLHD", "desc": "Small HD CINE 5 ONBOARD MONITOR", "sn": "C5AS24290016", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "LOUD SPEAKER", "desc": "12\u201d PROFESSIONAL LOUD SPEAKER (CTA)", "sn": "LSA \u2013 12DSP", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "THYPOCH/SIMERA-C LENSES", "desc": "21mm T1.5 THYPOCH/ SIMERA-C CINE LINE LENS, CASE", "sn": "W14J7100533", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "THYPOCH/SIMERA-C LENSES", "desc": "28mm T1.5 THYPOCH/ SIMERA-C CINE LINE LENS, CASE", "sn": "W13G7100387", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "THYPOCH/SIMERA-C LENSES", "desc": "35mm T1.5 THYPOCH/ SIMERA-C CINE LINE LENS, CASE", "sn": "W13J7100519", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "THYPOCH/SIMERA-C LENSES", "desc": "50mm T1.5 THYPOCH/ SIMERA-C CINE LINE LENS, CASE", "sn": "W13L7100328", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "THYPOCH/SIMERA-C LENSES", "desc": "75mm T1.5 THYPOCH/ SIMERA-C CINE LINE LENS, CASE", "sn": "W13N7100321", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "THYPOCH/SIMERA-C LENSES", "desc": "Nikon/RED ADAPTER T/SIMERA-C CINE LINE LENS, CASE", "sn": "K15P7100371", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "DJI", "desc": "DJI BATTERY STATION - TB50 / SUITCASE / DC POWER", "sn": "IN2BS", "qty": "1", "status": "OK" },
  { "type": "Grip", "category": "TILTA", "desc": "TA-LSR-B LIGHTWEIGHT SHOULDER RIG KIT W/ CASE", "sn": "SKU:6937134600285", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "CODEX MEDIA", "desc": "CODEX CARD READER (DC POWER)", "sn": "1071254", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "CODEX MEDIA", "desc": "CODEX CARD READER (USB-C)", "sn": "1056305", "qty": "1", "status": "OK" },
  { "type": "Camera", "category": "CODEX MEDIA", "desc": "CODEX CARD READER (USB-C)", "sn": "1076722", "qty": "1", "status": "OK" }
];